build: DNS_resolver.java
	javac DNS_resolver.java

clean:
	rm -r DNS_resolver.class
	rm -r DNSClass.class
	rm -r DNSRecordType.class
	rm -r ResponseAnalyzer.class
	rm -r ResponseAnalyzer\$$Query.class
	rm -r ResponseAnalyzer\$$Answer.class
	rm -r ResponseAnalyzer\$$Additional.class
	rm -r ResponseAnalyzer\$$Authority.class
	rm -r QueryBuilder.class
	

